# Generated by Django 4.1 on 2022-11-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description_short', models.CharField(max_length=500, verbose_name='Описание(краткое)')),
                ('description_long', models.TextField(max_length=500, verbose_name='Описание(полное)')),
                ('lng', models.IntegerField(verbose_name='Долгота')),
                ('lat', models.IntegerField(verbose_name='Широта')),
                ('images', models.ManyToManyField(related_name='images', to='places.image', verbose_name='Изображения')),
            ],
        ),
    ]
