# Generated by Django 4.1 on 2022-11-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_description_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на картинку'),
        ),
    ]
